# Generated by Django 5.1.1 on 2024-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_farmer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
